id: P1AD584AC
initial_creation_type: input
source_metadata:
  title: Marpa Lotsāwa Series
  language: bo
  description: 'Texts by and about the great Marpa Chökyi Lodrö (mar pa chos kyi blo
    gros, c.1012–1097), renowned as the founder of the Marpa Kagyü tradition and teacher
    of Milarepa:'
  volume:
    b5f2b6e4b1cc4185aeb390f250cc61de:
      title: A Combined Guru Yoga for Marpa, Mila, and Gampopa
      parent: Guru Yoga
    4987b1a9021e4a3ab95ec4a635b73b29:
      title: 'A Drop of Sunshine: A Guru Yoga for Lord Marpa'
      parent: Guru Yoga
    a3e60d973a374eaab7babbe0ac99d507:
      title: Guru Yoga of Lord Marpa Lotsāwa
      parent: Guru Yoga
    af25fb942d9e4f9aa6ab6a8fd5ff668c:
      title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the
        Three Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
      parent: Guru Yoga
    f78c8c10dd354eb981ada38e4c7de17d:
      title: Prayer to Lord Marpa, Consort and Heirs
      parent: Prayers
    15a23dd5d64e4bb3b5fcbd2218cf7554:
      title: 'Song of Devotion: A Prayer to Lord Marpa Lotsāwa'
      parent: Prayers
    8e629674ead141e9b6c8b23e4e27e3a2:
      title: 'The Melody of Complete Accomplishment: A Prayer to Those Praised as
        Ornaments of the Practice Lineage'
      parent: Prayers
created_at: '2022-03-01T00:43:52.484040'
last_modified_at: '2022-03-01T00:43:52.484043'
